{"name": "test_101_110[全部输入，输入验证码不正确]", "status": "passed", "parameters": [{"name": "username", "value": "'17854225747'"}, {"name": "password", "value": "'123456'"}, {"name": "verify_code", "value": "'1234'"}, {"name": "expectedtext", "value": "'验证码错误'"}], "start": 1596270238419, "stop": 1596270269252, "uuid": "0aafac81-0e1e-413a-8a9c-7e75b171181b", "historyId": "187ffd34cd742ff10cb44bbc5b8438cb", "testCaseId": "674c8a70a912fd8799a90691a3422221", "fullName": "cases.登录.test_login.Test_login#test_101_110", "labels": [{"name": "story", "value": "登录失败测试"}, {"name": "feature", "value": "登录功能"}, {"name": "parentSuite", "value": "cases.登录"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "Test_login"}, {"name": "host", "value": "PC-20180809BGFX"}, {"name": "thread", "value": "17008-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "cases.登录.test_login"}]}